version: '3.9'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: yotemi_admin
    restart: always
    tty: true
    networks:
      - yotemi

networks:
  yotemi:
    external: true